services:
  taskmanager:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - prometheus
    environment:
      - MONGO_URI=mongodb://mongo:27017

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ../configs/prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"
volumes:
  mongo-data:
